name: Continous Delivery .NET CORE
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
    CD:
        name: Connect server
        runs-on: ubuntu-20.04
        steps:
          - name: Access server
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USER_SSH }}
              key: ${{secrets.SSH_KEY}}
              port: 22
          - name: pull
            with: 
              uses: teste
              script: |
                cd clientes-netcore
                git pull origin master
