name: Continous Delivery .NET CORE
on:
  push:
    tags: v[0-9]+\.[0-9]+\.[0-9]+
  pull_request:
    tags: v[0-9]+\.[0-9]+\.[0-9]+

  workflow_dispatch:

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-20.04
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_SSH }}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            cd clientes-netcore
            git pull origin master
