name: Continous Delivery .NET CORE
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
    connect:
        name: Connect server
        runs-on: ubuntu-20.04
        steps:
          - name: Access server
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USER_SSH }}
              key: ${{secrets.SSH_KEY}}
              port: 22
    pull:
        needs: connect
        name: Pull Files on Server
        runs-on: ubuntu-20.04
        steps:
          - name: Access server
            run: |
                cd clientes-netcore
                git pull origin master
